### ISSUE TITLE
firefox stalling on windows (backslashes in path)

### ISSUE THREAD

**Issue by bboyle** [Polymer/web-component-tester#104]
I'm running the [seed-element](https://github.com/PolymerLabs/seed-element) tests on windows 8. Using `wct` on the command line.

Ran into an issue with Firefox stalling (v33.1 and v34.0.5). Here's the log from wct:
```
Web server running on port 64901 and serving from E:\Ben\Documents\Projects\GitHub\wct
Selenium server running on port 64902
ie 11.0.9600.17416       Beginning tests via http://localhost:64901/seed-element/test/index.html?cli_browser_id=2
ie 11.0.9600.17416       Tests passed
chrome 39                Beginning tests via http://localhost:64901/seed-element/test/index.html?cli_browser_id=0
chrome 39                Tests passed
firefox 34               Beginning tests via http://localhost:64901/seed-element%5Ctest%5Cindex.html?cli_browser_id=1
```

IE and Chrome appear to be converting backslashes for the URL, Firefox has encoded them and thus can't find the file.

Would a potential fix be to use node's [url.resolve()](http://nodejs.org/api/url.html#url_url_resolve_from_to) at this point?
https://github.com/Polymer/web-component-tester/blob/master/runner/browserrunner.js#L95

```js
this.browser.get(require('url').resolve(host, path) + extra, function(error) {
```

Fixes the issue when I run the tests.

**Comment by warpech** [comment]
+1

Screenshot below:

![screenshot wct](https://cloud.githubusercontent.com/assets/566463/5738661/1bf6e7ee-9bef-11e4-9717-5a535c891766.png)

**Comment by tpluscode** [comment]
:+1:
