### ISSUE TITLE
Tests hosted on web server do not work in FF/Safari

### ISSUE THREAD

**Issue by atotic** [Polymer/web-component-tester#112]
Are you aware that WCT does not work in Firefox/Safari? Polymer 0.5.2

I have two Polymer projects, and I can't run my test suites in FF/Safari when hosted on a web server. 

First project is a very simple test case [fancy-doc-viewer](https://github.com/atotic/fancy-doc-viewer). It fails because custom elements created with doc.createElement have not been upgraded. Tried Platform.flush, no go. 

Running same tests from command line I get

    chrome 40 (2/0/0)                       chrome 42 (2/0/0)                     
    firefox 35 (0/0/0)                      safari 8.0.2 (error)          

Second project is more complex, multiple test files (but fails with single file too) [nodepook](https://github.com/atotic/nodepook). Here FF does seem to execute my test suite at all, I can't trigger any breakpoints inside the suite.

Tried looking into it, nothing obvious pops out, and it'd take me a bit to get up to speed.

**Comment by nevir** [comment]
Hmm, it definitely should be working in firefox - safari is a bit weird (requires a manual step to install the selenium plugin for it, see https://code.google.com/p/selenium/issues/detail?id=7933)

WCT defers all tests by default until the elements have upgraded (`polymer-ready`).

However, I think you're running into trouble by calling `createElement` early. For firefox/etc (polyfilled), you're ending up calling that before the custom element has registered. Nodes created that way sadly do not get upgraded (they must be in the document)

try this: https://github.com/atotic/fancy-doc-viewer/pull/1

**Comment by nevir** [comment]
General mochaism: any code inside `describe`/`suite` is executed immediately (synchronously), but anything in `test`/`before*`/etc are async (and WCT defers them further to wait for polymer-ready)

**Comment by atotic** [comment]
You are right. My problem was creating fixtures outside of `before`. It all works now.
Polyfill stuff can be tricky....

**Comment by nevir** [comment]
Yeah :( it's hard to give good errors about it too, unfortunately :(
