### ISSUE TITLE
Unable to install web-component-tester on Linux Ubuntu

### ISSUE THREAD

**Issue by jmaudet** [Polymer/web-component-tester#113]
Hi, I am not able to install web-component-tester

Linux 3.2.0-74-generic
/usr/local/bin/npm install -g web-component-tester@latest

Looks to be during a step using Selenium

Any idea?

Here are the logs:
sudo npm install -g web-component-tester@latest
 
> sauce-connect-launcher@0.9.3 postinstall /usr/local/lib/node_modules/web-component-tester/node_modules/sauce-connect-launcher
> node scripts/install.js

 
> ws@0.5.0 install /usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> selenium-standalone@2.44.0 install /usr/local/lib/node_modules/web-component-tester/node_modules/selenium-standalone
> node install.js

Installation finished

Error: Could not download http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
    at getDownloadStream (/usr/local/lib/node_modules/web-component-tester/node_modules/selenium-standalone/install.js:156:36)
    at installSelenium (/usr/local/lib/node_modules/web-component-tester/node_modules/selenium-standalone/install.js:51:3)
    at /usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:570:21
    at /usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:249:17
    at /usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:46:24)
    at async.each (/usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:248:13)
    at Object.map (/usr/local/lib/node_modules/web-component-tester/node_modules/async/lib/async.js:219:23)

> ws@0.4.31 install /usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/local/lib/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm ERR! Linux 3.2.0-74-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "web-component-tester@latest"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE

npm ERR! selenium-standalone@2.44.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the selenium-standalone@2.44.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the selenium-standalone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls selenium-standalone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/audetj/src/CfD/Src/WebUi/npm-debug.log

**Comment by jmaudet** [comment]
I have setup my proxy, I am able to download manually http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar using wget...

**Comment by nevir** [comment]
I'm not sure I have enough detail to track this one down :(

For reference, the logic for fetching selenium is over at https://github.com/vvo/selenium-standalone/blob/master/lib/install.js#L137-159 - it looks like it's eating any sort of error message that request throws though.

**Comment by nevir** [comment]
I'm closing this issue in favor of https://github.com/vvo/selenium-standalone/pull/64 - feel free to reopen if it still looks like an issue w/ WCT!

**Comment by nevir** [comment]
@vvo just pushed a new version of `selenium-standalone` w/ that patch included; hopefully it helps us diagnose & figure out what needs fixin'!
