### ISSUE TITLE
cache-bust via a mechanism other than URL

### ISSUE THREAD

**Issue by nevir** [Polymer/web-component-tester#114]
The current `bust=193819028408` approach breaks the debugger (as breakpoints are keyed by source URL) - they'll disappear after a refresh.

Maybe it's enough to just have the WCT express server go with no-cache headers; and not support cache busting otherwise?

**Comment by pflannery** [comment]
+1 drives me mad...always having to comment out [here](https://github.com/Polymer/web-component-tester/blob/master/browser.js#L6409) and [here](https://github.com/Polymer/web-component-tester/blob/master/browser.js#L6588)

**Comment by garlicnation** [comment]
+100

I just use debugger statements and it's extremely annoying.
