### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by jannakha** [Polymer/web-component-tester#120]
I'm running tests both on local and on sauce labs, so I have configuration for both options:
module.exports = {
  verbose: true,
  plugins: {
    local: {
      browsers: ["chrome", "firefox"]
    },
    sauce: {
      browsers: [
        {
          "browserName": "safari",
          "platform": "OS X 10.9",
          "version": "7"
        }
]
    }
  }
};

when I start tests: wct --plugin sauce or wct --plugin local I expect only once configuration to run either locally OR on SauceLabs

currently both configurations will run - I'm observing tests running on SauceLabs and locally from either command (wct --plugin sauce or wct --plugin local)

Please, explain if this is expected or not?

Cheers,
Janna

**Comment by nevir** [comment]
Hmm, the current behavior is for the command line flags to merge options into any configuration you have specified via `wct.conf.js`.

Also, each plugin currently kicks in if there are _any_ browsers specified in their config. (So, just running `wct` on its own should run both w/ your current environment).

Hmm.

It might be best to have a way of blacklisting plugins from the command line. `--no-plugin`?

Alternatively, perhaps having an additional flag per plugin might be handy, so that you can specify default configuration without having the plugin turn on:

```js
local: {
  enabled: false,
  browsers: ['chrome', 'firefox'],
  ...
}
```

**Comment by ckortekaas** [comment]
I've found that a good workaround while wct.conf.js can't contain both local and sauce plugins without running them both is to stop using wct.conf.js and just use the command line (and put the command inside a shells script.

For example a script to run sauce tests like sauce.sh:

```
#!/bin/bash
wct --plugin sauce --sauce-username=${SAUCE_USERNAME} --sauce-access-key=${SAUCE_ACCESS_KEY} \
--sauce "OSX 10.9/safari@7.0" \
--sauce "Windows 8.1/chrome@39.0" \
--sauce "Windows 8.1/firefox@35.0" \
--sauce "linux/android@4.4" \
--sauce "Windows 8.1/internet explorer@11.0"
```

or a script to run the tests with local browsers like local_tests.sh:

```
#!/bin/bash
wct --plugin local \
--local chrome \
--local firefox \
#--local safari
```

If you keep the lines broken with \ chars it's still pretty readable compared with json.

**Comment by nevir** [comment]
Alright, once I release the next version of WCT, you'll be able to specify `disabled: true` in a plugin configuration to indicate default configuration w/o turning the plugin on.

Then you can `wct --plugin NAME` or `{plugins: ['NAME']}` or `{plugins: {NAME: {disabled: false}}}` to activate it

**Comment by bennypowers** [comment]
I hate to wake the dead, but when `plugins: {sauce}` is specified in wct.conf.json, I expect running `polymer test -l safari` to only run local safari tests, as the inline documentation explains. Instead it first tries to run sauce.

Similarly, I expect `polymer test --skip-plugin sauce -l safari` to only run on safari but it instead runs all local browsers.
