### ISSUE TITLE
Running 'wct` generates error

### ISSUE THREAD

**Issue by donnapep** [Polymer/web-component-tester#121]
I get the following error message when running the `wct` command - "The following browsers were not found: aurora. (All installed browsers found: chrome, canary, firefox, safari)".

No tests attempt to run past this point. It just goes back to the command prompt.

**Comment by nevir** [comment]
You're running `wct` without any arguments and get that? Hmm.

Do you have a `wct.conf.js` present in the project, or in your home directory?

**Comment by losttime** [comment]
I'm having the same problem. Aurora is reported as missing while chrome, canary, firefox, and safari are reported as found. It does not seem like any tests are being run.

Initially I did not have  a `wct.conf.js` file in the project or my home directory. Now I have a `wct.conf.js` file in the project and the same thing happens.

Here's the output with `verbose` set to `true` in `wct.conf.js`:
```
$ wct
step: loadPlugins
step: configure
hook: configure
hook done: configure with error: The following browsers were not found: aurora. (All installed browsers found: chrome, canary, firefox, safari)



The following browsers were not found: aurora. (All installed browsers found: chrome, canary, firefox, safari)

$
```
Running OS X Yosemite 10.10.2
web-component-tester: 2.0.1

**Comment by nevir** [comment]
Alright, I'm going to yank 2.1.x for a bit while I dig through these issues. Hoping to have it all fixed by end of next week, but for the time being I'm going to recommend reverting back to 2.0.x

Apologies!

**Comment by donnapep** [comment]
@nevir OK, thanks. And to your earlier question, I did not have a `wct.conf.js` file included anywhere.

**Comment by nevir** [comment]
Awesome, thanks! That narrows it down for me
