### ISSUE TITLE
npm thinks 2.0.5 is the latest version, should be 2.1.3

### ISSUE THREAD

**Issue by ckortekaas** [Polymer/web-component-tester#125]
Hi there,

Is there something you need to do to make npm realise there's a new version? I thought all you had to do was update your package.json, which you've done.

Until then, to get 2.1.3 I need to install using:
```
npm install -g Polymer/web-component-tester
```

And this probably isn't ideal?

**Comment by addyosmani** [comment]
@nevir if you go ahead and `npm publish`, this should be all good. 

Silly tip: I love using https://www.npmjs.com/package/npm-release for managing releases of my packages. Makes it a one liner to bump package, tag and publish to npm a breeze :)

**Comment by nevir** [comment]
I yanked it due to outstanding issues (wasn't as backwards compatible as I
thought); did you end up pulling part of it? (Maybe I missed something)

**Comment by addyosmani** [comment]
Makes sense. npm currently shows the latest version as 2.0.5 but I'm guessing users see the version in https://github.com/Polymer/web-component-tester/blob/master/package.json and are expecting those to be in sync. I'd close this issue when you're happy to republish a version you're happy with.

**Comment by nevir** [comment]
Yeah, sorry for the confusion! I hope to have a working 2.1.x version
re-released in a day or two

**Comment by nevir** [comment]
Alrighty, I believe I've resolved all the outstanding issues! Just pushed `2.2.0`
