### ISSUE TITLE
Context.prototype.emitHook with an additionnal argument doesn't work

### ISSUE THREAD

**Issue by MaisBouh** [Polymer/web-component-tester#127]
Hello and sorry for my bad english.

I'm trying to hook **prepare:webserver** for configuring other routes.
But looking in the sources, i found that code at line 87 :
`var hookArgs = [null].concat(Array.prototype.slice.call(arguments, 1, arguments.length - 1));`
and it doesn't give me the app in first argument of my handler. If i replace this line by
`var hookArgs = [null].concat(Array.prototype.slice(1, arguments.length - 1)).concat([done]);` it works.
Is it a bug or am i doing the wrong way to configure the webserver ?

Thanks in advance,

Adrien

**Comment by Klathmon** [comment]
I also noticed this. I think there might be a bug somewhere here...

In my case i'm trying to hook into the "prepare:webserver" hook. I'm expecting my hook to get:

"prepare:webserver", express, done

But what i actually am getting is:

"prepare:webserver", done

No amount of screwing with the slice of the arguments is helping, so either i'm doing something very wrong or there is a fun bug somewhere.

**Comment by nevir** [comment]
Wow, how have I gotten this long without knowing that `arguments` maintains references to the associated variables? (also sorry about the hasty refactoring)

http://jsbin.com/ginufe/2/edit?js,console (bah! strict mode avoids this: http://jsbin.com/sajegukati/1/edit?js,console)

Anyway, pushed `v2.2.2` w/ this fixed.

**Comment by MaisBouh** [comment]
Thanks a lot !

**Comment by Klathmon** [comment]
Thanks for such a quick turnaround!
