### ISSUE TITLE
Test suite executed before polymer-ready is called (Urgent)

### ISSUE THREAD

**Issue by shailesh17mar** [Polymer/web-component-tester#129]
So, I have created a table element which exists in light dom because of I am using a jquery plugin. I am trying to write test cases for the component using web-component-tester. 

The code snippet is same as the seed-element 

```html
"<t-table id="tablecomponent" sortData="false"  multiSelect searchable edittable dispstyle="bordered" >
				<t-column dataValue="fruit" displayValue="Name"  class="footable-first-column" cellTemplate="test"></t-column>
				<t-column dataValue="alice" displayValue="Role"></t-column>
				<t-column data-sort-ignore="true" dataValue="bill" displayValue="Last signed in" ></t-column >
				<t-column dataValue="casey" class="footable-last-column" displayValue="Status" ></t-column>
				<template id="test">
					<a href="{{value}}">{{value}}</a>
				</template>	
		</t-table>	"



</body>
<script>
var table=document.querySelector('t-table');
suite('basic',function(){
	  test('page is loaded with table',function(done){
	  	
	    assert.isTrue(table != null, 'table present on page.');
	    done();
	  });

	   test('table should be instantiated with default values',function(done){
	   	var table=document.querySelector('t-table');
	  	assert.isFalse(table.dataRows.length==0,'sortData should be false by default');
	  	done();
		});


});
```

I am not able to access properties by 'table' variable from which I concluded that the 'polymer-ready' event might not have been called. So, Can anyone guide me what is it that I am doing wrong here.

**Comment by nevir** [comment]
Can you post the entire test file?

(as a guess, though: make sure you are importing the definition for t-table at the top of the test. Also, if you are running this in a browser other than chrome, make sure that you're loading webcomponents.js as well)

**Comment by nevir** [comment]
Also, rather than:

```js
var table=document.querySelector('t-table');
suite('basic',function(){
...
```

Try this:

```js
var table;
suite('basic',function(){
  beforeEach(function(){
    table=document.querySelector('t-table');
  }
  ...
```

Your element will not have upgraded before `polymer-ready`, (only `test` functions wait for `polymer-ready`, inline scripts and code within `suite` execute immediately)

**Comment by shailesh17mar** [comment]
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>t-table basic tests</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <script src="../../../bower_components/webcomponentsjs/webcomponents.js"></script>
  <script src="../../../bower_components/web-component-tester/browser.js"></script>

  <link rel="import" href="../t-table.html" >
  <link rel="import" href="../t-column.html">
</head>
<body >

		<t-table multiSelect sortData edittable searchable dispStyle="striped" pageCount="5" searchOn="fruit">
				<t-column hideOn="phone" dataValue="fruit" displayValue="Name"    cellTemplate="test"></t-column>
				<t-column hideOn="tablet" dataValue="alice" displayValue="Role"></t-column>
				<t-column data-sort-ignore="true" dataValue="bill" displayValue="Last signed in" ></t-column >
				<t-column dataValue="casey"  displayValue="Status" ></t-column>
				<template id="test">
					<a href="{{value}}">{{value}}</a>
				</template>	
		</t-table>	



</body>
 <script>


suite('<t-table>',function(){
	
	var testTable=null;

	before(function(){
		testTable=document.querySelector('t-table');
		testTable.dataRows=[
					{ "fruit":"apple",	"alice": 4,	"bill": 10,	"casey": 2 },
					{ "fruit":"banana",	"alice": 0,	"bill": 4,	"casey": 0 },
					{ "fruit":"grape",	"alice": 2,	"bill": 3,	"casey": 5 },
					{ "fruit":"pear",	"alice": 4,	"bill": 2,	"casey": 8 },
					{ "fruit":"apple",	"alice": 4,	"bill": 10,	"casey": 2 },
					{ "fruit":"banana",	"alice": 0,	"bill": 4,	"casey": 0 },
					{ "fruit":"grape",	"alice": 2,	"bill": 3,	"casey": 5 }
			];
	});

	beforeEach(function(){
		testTable=document.querySelector('t-table');
	});

  	test('page is loaded with table',function(){
    	assert.isTrue(testTable != null, 'table present on page.');
  	});

   test('table should be instantiated with default sortData value as false',function(){
  		assert.isFalse(testTable.sortData,'sortData should be false by default');
	});

    test('table should be instantiate with default edittable value as false',function(){
    	assert.isTrue(testTable.edittable,'table should not be edittable by default');
    });


});




</script>
</html>


Still not working.

**Comment by dapullar** [comment]
You are mixing BDD and TDD styles. See #106
>The "BDD" interface provides:
`describe()`, `it()`, `before()`, `after()`, `beforeEach()`, and `afterEach()`

>The "TDD" interface provides:
`suite()`, `test()`, `suiteSetup()`, `suiteTeardown()`, `setup()`, and `teardown()`.

**Comment by nevir** [comment]
Hah! Thanks for catching that @dapullar
