### ISSUE TITLE
Make it possible to load browser.js once

### ISSUE THREAD

**Issue by oderby** [Polymer/web-component-tester#131]
Currently, afaict, WCT assumes every test file has a 
```html
<script src="../web-component-tester/browser.js"></script>
```
tag, as that's how it determines where to load the environment.js file from.

However, we have several common methods/utils/stubs in ../test-tools/utils.html that we also need to include in all our test files. It would be super nice to be able to just do
```html
<link rel="import" href="../test-tools/utils.html">
```
alone in all our test files, and have utils.html load browser.js.

Currently, we can work around this by manually loading environment.js via something like the following in utils.html. 

```html
<script>
    WCTPrefix = "foo";
</script>
<script src="../web-component-tester/browser.js?skipEnv"></script>
<script src="../web-component-tester/environment.js"></script>
```

but hopefully there's a better way?

**Comment by oderby** [comment]
or maybe there's a better way? Open to suggestions. We essentially have several dozen custom web components, and we're currently specifying a single wct.conf.js file in the root directory with the suites key set. e.g.
```js
    suites: [
        'components/foo-*/*.test.html'
    ],
```
And then all our custom elements folders define the element (components/foo-bar/foo-bar.html) and the test html (components/foo-bar/foo-bar.test.html).

**Comment by justinfagnani** [comment]
I think we can track this in #133 with the addition that both the generated index.html and injected scripts should be more customizable.
