### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by santokhsingh** [Polymer/web-component-tester#132]
Installation is stuck while installing IEdriverServer and installation is not completing.
Command used: npm install -g web-component-tester

**Comment by santokhsingh** [comment]
Fixed.

**Comment by nevir** [comment]
Curious: what was the fix? (in case someone else runs into that)

**Comment by santokhsingh** [comment]
It just started working after a while, so I just assumed that IE specific dependency is fixed on remote repository.
