### ISSUE TITLE
Functional testing

### ISSUE THREAD

**Issue by Shadowfaxenator** [Polymer/web-component-tester#134]
How can I write functional tests inside html files?
For example I want to write a functional test for a component `<order-page>`
If not with polymer I use `require('webdriverio')` in NodeJs. And write test in nodejs. How to include webdriver into html page to make `wct test.html` run functional test on selenium?

**Comment by nevir** [comment]
Unfortunately there isn't support for making webdriver calls from within WCT's environment (which is already being driven by webdriver)

We'd like to support this (#76), but probably won't have bandwidth to set that up for a while.  Merging this into #76.

**Comment by danielvanmil** [comment]
"which is already being driven by webdriver". Is there any more documentation on the design of the web-component-tester and how it can be used? Are the test cases in the test html page transformed to selenium commands for example? Can I only invoke methods that are defined on the web components API? Functional test not possible yet like test drag and drop etc.?

Thanks.
