### ISSUE TITLE
Not able to install WCT

### ISSUE THREAD

**Issue by yelurinaveen** [Polymer/web-component-tester#138]
I am facing issues while trying to install WCT through npm. Below is the error trace

Command:
npm install web-component-tester --save-dev

Log Trace:
selenium-standalone installation starting

selenium install:
from: http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
to: c:\Users\nyeluri\Workspace\Naveen_Lane\TestPoly\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\selenium-server\2.44.0-server.jar

chrome install:
from: http://chromedriver.storage.googleapis.com/2.13/chromedriver_win32.zip
to: c:\Users\nyeluri\Workspace\Naveen_Lane\TestPoly\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\chromedriver\2.13-x64-chromedriver

ie install:
from: http://selenium-release.storage.googleapis.com/2.44/IEDriverServer_x64_2.44.0.zip
to: c:\Users\nyeluri\Workspace\Naveen_Lane\TestPoly\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\iedriver\2.44.0-x64-IEDriverServer.exe

[Error: Could not download http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar: Error: getaddrinfo ENOTFOUND]

npm ERR! wct-sauce@1.2.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the wct-sauce@1.2.0 postinstall script.
npm ERR! This is most likely a problem with the wct-sauce package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls wct-sauce
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web-component-tester" "--save-dev"
npm ERR! cwd c:\Users\nyeluri\Workspace\Naveen_Lane\TestPoly
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by nevir** [comment]
I'm assuming this was fixed w/ the bump to the latest version of selenium-standalone (2.45). Please reopen if you're still having trouble
