### ISSUE TITLE
wct-local package problems

### ISSUE THREAD

**Issue by dapullar** [Polymer/web-component-tester#139]
Looks like the wct-local@1.3.0 dependencies now requires the newer selenium drivers for `selenium-standalone` which was updated to `4.2.0`

`2.14-x64-chromedriver` yet it installs `2.13-x64-chromedriver`, IE driver from `2.44` to `2.45.0.-x64-IEDriverServer` Selenium driver from `2.44` to `2.45.0.-server.jar`. Upon running `wct` an error is thrown for the the missing drivers. I manually updated them and all worked as normal. 

This seems like an issue with with wct-local `postinstall.js` which states the `CHROME_VERSION = 2.13` and `BASE_VERSION = 2.44.0`.

Since I havent been able to look too much into this just yet, I maybe completely wrong, so I have posted the issue on this repo since the error may reside with wct itself.

**Comment by CoreMaker** [comment]
+1

**Comment by donnapep** [comment]
Also a problem for me.

**Comment by dapullar** [comment]
If you want a work around, just:
1. `npm install web-component-tester` 
2. `npm shrinkwrap`
3. edit `npm-shrinkwrap.json`:

**Comment by dapullar** [comment]
If you want a work around:

1. `npm install web-component-tester` 
2. `npm shrinkwrap`
3. edit `npm-shrinkwrap.json`:
- search and change `wct-local` to `v1.2.1`
- change `selenium-standalone` to `v3.2.0`
4. do a fresh `npm install` to retrieve working versions

**Comment by dapullar** [comment]
If you want a work around:

1. `npm install web-component-tester` 
2. `npm shrinkwrap`
3. edit `npm-shrinkwrap.json`:
  * search and change `wct-local` to `v1.2.1`
  * search and change `selenium-standalone` to `v3.2.0`
4. do a fresh `npm install` to retrieve working versions

There is a pull request pending for this, so it shouldn't be too long until this is resolved.

**Comment by nevir** [comment]
Pushed those changes out (sorry about that)! Can you please bump to the latest `web-component-tester` and `wct-local` and verify that the issue's fixed for you?

**Comment by cnugithub** [comment]
just got the latest web-component-tester, verified wct-local.
I need to remove IE from the running browsers list, where can I do that (where is wct-config.js or something?).. our application will not run properly on IE so want to skip for now during evaluation

mean while, when I hit wct, I get IE errors..

ie 11.0.9600.17496       Tests failed: {"state":"unhandled error","sessionId":null,"hCode":1049064799,
"value":{"additionalInformation":"\nDriver info: org.openqa.selenium.ie.InternetExplorerDriver","local
izedMessage":"Unexpected error launching Internet Explorer. Protected Mode settings are not the same f
or all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
 (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 192 mi
lliseconds\nBuild info: version: \u00272.45.0\u0027, revision: \u00275017cb8\u0027, time: \u00272015-0
2-26 23:59:50\u0027\nSystem info: host: \u0027UC180514-TPD-A\u0027, ip: \u002710.208.32.241\u0027, os.
name: \u0027Windows 7\u0027, os.arch: \u0027amd64\u0027, os.version: \u00276.1\u0027, java.version: \u
00271.8.0_31\u0027\nDriver info: org.openqa.selenium.ie.InternetExplorerDriver","systemInformation":"S
ystem info: host: \u0027UC180514-TPD-A\u0027, ip: \u002710.208.32.241\u0027, os.name: \u0027Windows 7\
u0027, os.arch: \u0027amd64\u0027, os.version: \u00276.1\u0027, java.version: \u00271.8.0_31\u0027","s
upportUrl":null,"cause":null,"stackTrace":[{"fileName":null,"nativeMethod":true,"methodName":"newInsta
nce0","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":513928194,"lineNumber":-2,"class
":"java.lang.StackTraceElement"},{"fileName":null,"nativeMethod":false,"methodName":"newInstance","cla
ssName":"sun.reflect.NativeConstructorAccessorImpl","hCode":-432498851,"lineNumber":-1,"class":"java.l
ang.StackTraceElement"},{"fileName":null,"nativeMethod":false,"methodName":"newInstance","className":"
sun.reflect.DelegatingConstructorAccessorImpl","hCode":-2147429624,"lineNumber":-1,"class":"java.lang.
StackTraceElement"},{"fileName":null,"nativeMethod":false,"methodName":"newInstance","className":"java
.lang.reflect.Constructor","hCode":-1851634561,"lineNumber":-1,"class":"java.lang.StackTraceElement"},
{"fileName":"ErrorHandler.java","nativeMethod":false,"methodName":"createThrowable","className":"org.o
penqa.selenium.remote.ErrorHandler","hCode":514255486,"lineNumber":204,"class":"java.lang.StackTraceEl
ement"},{"fileName":"ErrorHandler.java","nativeMethod":false,"methodName":"throwIfResponseFailed","cla
ssName":"org.openqa.selenium.remote.ErrorHandler","hCode":1091067089,"lineNumber":162,"class":"java.la
ng.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"execute",
"className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":1767885086,"lineNumber":599,"class":"
java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"st
artSession","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":-1182648234,"lineNumber":
240,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"me
thodName":"startSession","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":-1182648249,
"lineNumber":225,"class":"java.lang.StackTraceElement"},{"fileName":"InternetExplorerDriver.java","nat
iveMethod":false,"methodName":"run","className":"org.openqa.selenium.ie.InternetExplorerDriver","hCode
":-1132542939,"lineNumber":182,"class":"java.lang.StackTraceElement"},{"fileName":"InternetExplorerDri
ver.java","nativeMethod":false,"methodName":"\u003cinit\u003e","className":"org.openqa.selenium.ie.Int
ernetExplorerDriver","hCode":-2098680252,"lineNumber":174,"class":"java.lang.StackTraceElement"},{"fil
eName":"InternetExplorerDriver.java","nativeMethod":false,"methodName":"\u003cinit\u003e","className":
"org.openqa.selenium.ie.InternetExplorerDriver","hCode":-2098680276,"lineNumber":150,"class":"java.lan
g.StackTraceElement"},{"fileName":null,"nativeMethod":true,"methodName":"newInstance0","className":"su
n.reflect.NativeConstructorAccessorImpl","hCode":513928194,"lineNumber":-2,"class":"java.lang.StackTra
ceElement"},{"fileName":null,"nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.
NativeConstructorAccessorImpl","hCode":-432498851,"lineNumber":-1,"class":"java.lang.StackTraceElement
"},{"fileName":null,"nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.Delegatin
gConstructorAccessorImpl","hCode":-2147429624,"lineNumber":-1,"class":"java.lang.StackTraceElement"},{
"fileName":null,"nativeMethod":false,"methodName":"newInstance","className":"java.lang.reflect.Constru
ctor","hCode":-1851634561,"lineNumber":-1,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultD
riverProvider.java","nativeMethod":false,"methodName":"callConstructor","className":"org.openqa.seleni
um.remote.server.DefaultDriverProvider","hCode":-2096353712,"lineNumber":59,"class":"java.lang.StackTr
aceElement"},{"fileName":"DefaultDriverProvider.java","nativeMethod":false,"methodName":"newInstance",
"className":"org.openqa.selenium.remote.server.DefaultDriverProvider","hCode":1201680291,"lineNumber":
53,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultDriverFactory.java","nativeMethod":false
,"methodName":"newInstance","className":"org.openqa.selenium.remote.server.DefaultDriverFactory","hCod
e":-1365021422,"lineNumber":54,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java
","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.remote.server.DefaultSessi
on$BrowserCreator","hCode":2056168463,"lineNumber":214,"class":"java.lang.StackTraceElement"},{"fileNa
me":"DefaultSession.java","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.re
mote.server.DefaultSession$BrowserCreator","hCode":2056168250,"lineNumber":1,"class":"java.lang.StackT
raceElement"},{"fileName":null,"nativeMethod":false,"methodName":"run","className":"java.util.concurre
nt.FutureTask","hCode":424519275,"lineNumber":-1,"class":"java.lang.StackTraceElement"},{"fileName":"D
efaultSession.java","nativeMethod":false,"methodName":"run","className":"org.openqa.selenium.remote.se
rver.DefaultSession$1","hCode":-255143475,"lineNumber":168,"class":"java.lang.StackTraceElement"},{"fi
leName":null,"nativeMethod":false,"methodName":"runWorker","className":"java.util.concurrent.ThreadPoo
lExecutor","hCode":-1208971944,"lineNumber":-1,"class":"java.lang.StackTraceElement"},{"fileName":null
,"nativeMethod":false,"methodName":"run","className":"java.util.concurrent.ThreadPoolExecutor$Worker",
"hCode":-166011880,"lineNumber":-1,"class":"java.lang.StackTraceElement"},{"fileName":null,"nativeMeth
od":false,"methodName":"run","className":"java.lang.Thread","hCode":1432591020,"lineNumber":-1,"class"
:"java.lang.StackTraceElement"}],"suppressed":[],"message":"Unexpected error launching Internet Explor
er. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the s
ame value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace inf
ormation)\nCommand duration or timeout: 192 milliseconds\nBuild info: version: \u00272.45.0\u0027, rev
ision: \u00275017cb8\u0027, time: \u00272015-02-26 23:59:50\u0027\nSystem info: host: \u0027UC180514-T
PD-A\u0027, ip: \u002710.208.32.241\u0027, os.name: \u0027Windows 7\u0027, os.arch: \u0027amd64\u0027,
 os.version: \u00276.1\u0027, java.version: \u00271.8.0_31\u0027\nDriver info: org.openqa.selenium.ie.
InternetExplorerDriver","hCode":1623372482,"class":"org.openqa.selenium.remote.SessionNotFoundExceptio
n","buildInformation":{"buildRevision":"5017cb8","buildTime":"2015-02-26 23:59:50","releaseLabel":"2.4
5.0","hCode":1151598210,"class":"org.openqa.selenium.internal.BuildInfo"},"screen":null},"class":"org.
openqa.selenium.remote.Response","status":13}

**Comment by dapullar** [comment]
@cnugithub you can set these preferences in your `wct.conf.js`

@nevir no need to be sorry, runs like a beauty, even plays nicely with firefox 36 now. cheers.

**Comment by nevir** [comment]
Glorious!
