### ISSUE TITLE
Struggling to parse some sentences in readme file

### ISSUE THREAD

**Issue by akc42** [Polymer/web-component-tester#145]
This is my first attempt at trying to use web-component-tester and I am struggling to understand the meaning of a couple of sentences in the README file.

Firstly just under the heading ".js suites"

```
Or, you can write tests in separate `.js` sources, which run in the context of
your text index. 
```

what is a "text index" ?  Does that mean "test index"?  If so does that mean an .html file, and if it does,  does it have to be called index.html? (see my second confusion below)

Secondly under the heading "Running your tests/wct"  
```
By default, any tests under `test/` will be run. You can run particular files
(or globs of files) via `wct path/to/files`.
```

If I run the command (or rather I get gulp to run it after watching for changes)
```
wct elements/**/*.test.html
```
will that automatically run all tests that I have stored next to my elements .html files. (I don't want a separate test directory to test the client, I want to store my tests with the elements).

If I do this, does it also run tests in the (default - or specified in wct-conf.js under the "suites" config paramters) "test/" directory?

I am hoping NOT, because I want to reserve that for running tests on custom elements developed solely for testing my ajax server side scripts.  These would reside in a different directory hierarchy to by client side app

What files does it run under test/  all .html and .js files? just html files?  I am unsure how to reconcile this statement with the statement in the ".js suites" if I have both an html file and a js file in the same directory. Does it only run tests in this directory, or also subdirectories beneath it.?

Thirdly just under the heading "Running your tests/web server" it says

```
You'll need to save WCT's `browser.js` in order to go this route.
```

What does "save" mean - where do I save it? and why?

Also, if the index.html file is served by a web server can I start the tests from the command line?

Fourthly - the section "Nested Suites" appears to be a sub section of "Running your tests/web server"

Does the WCT.Loadsuites command only work in this scenario?  or would it work in the context of tests started from the command line?

I am trying to plan a scenario using gulp  where I have a client as a polymer Single Page Application based in an `app/` directory  where the elements need module testing, but I want to store the tests with the elements themselves, but then I have some php scripts to catch all the ajax calls from the client.  In the test scenario all these ajax calls will be faked using sinon so won't be stored in the `app/` directory itself

So I want to develop a different polymer client in a `server/` directory which is served by nginx so it can also run the php scripts the main client will use mapped into the `serv/` subdirectory of server.  This client will just be a series of core-ajax calls to exercise these scripts.  Again a separate gulp task will initiate these tests if that is possible (I assume maybe a plugin like used for wct:remote)

Finally I want to also develop some integration tests to run against a `dist/` directory where the client and server come together (copied by a gulp task)

**Comment by akc42** [comment]
After a lot of poking around with node-inspector to see what is going on, I can at least confirm that running
```
wct app/elements/**/*.test.html
```
does not use the suites setting in the default config file, but exclusively runs the tests that that file glob defines.

**Comment by nevir** [comment]
Sorry about the delayed response, and thanks for the in-depth feedback! I'm currently integrating that feedback, and attempting to clarify the README in response

In the meantime, here's some specific responses:

---

> what is a "text index" ?  Does that mean "test index"?  If so does that mean an .html file, and if it does,  does it have to be called index.html?

This is the initial file run in the browser (it may or may not be actually called `index.html`), that makes a call to `WCT.loadSuites` w/ all the tests you wish to run.

---

> If I run the command (or rather I get gulp to run it after watching for changes)
> ```
> wct elements/**/*.test.html
> ```
> will that automatically run all tests that I have stored next to my elements .html files. 

Yup, that's how it should behave!

---

> If I do this, does it also run tests in the (default - or specified in wct-conf.js under the "suites" config paramters) "test/" directory?

No: by specifying `elements/**/*.test.html` as positional arguments to `wct`, you are overriding the `suites` config parameter with `["elements/**/*.test.html"]` (or, well, the expanded form of it, depending on which shell you use)

---

> Thirdly just under the heading "Running your tests/web server" it says
> ```
> You'll need to save WCT's `browser.js` in order to go this route.
> ```
> What does "save" mean - where do I save it? and why?

WCT can be run both on the command line, and also purely in the browser - `browser.js` is all of its browser-side logic (`WCT.loadSuites` and all that). 

---

> Does the WCT.Loadsuites command only work in this scenario?  or would it work in the context of tests started from the command line?

It'll work in both cases, as long as you always have a `<script src="../web-component-tester/browser.js">` in your tests. When run via the CLI, [WCT serves its bundled copy of `browser.js`](https://github.com/Polymer/web-component-tester/blob/master/runner/webserver.js#L28-31)
