### ISSUE TITLE
WCT --root does not seem to work

### ISSUE THREAD

**Issue by rjrahul** [Polymer/web-component-tester#147]
I have installed act as npm global install. My project is express based and tests are stored under subdirectories of test/client.

when running "wct --root=test/client" from my project root it gives error "No test suites were found matching your configuration"

There is no example of its use when seen using wct --help

**Comment by nevir** [comment]
Root sets the webserver root, rather than indicating the tests to run (by
setting root to test/client, your tests will not be able to reference any
files above that path)

I think you want to run it without that flag, I.e.: `wct test/client`

**Comment by rjrahul** [comment]
It looks like the root sets the root directory of the project... My problem is a little different... I have following directory structure
myproj
|__app.js
|__bower_components
|__public
|__test
     |__client
          |__test.html

My application is an express app (running on port 3000) exposing a virtual root called /app. It also exposes API on browser path /api. My components need to call the /api endpoint to access the data and my components and bower components are served through virtual root /app (configured through express-static).

Problem is when I use wct to say "wct --webserver-port=3000" it seems to be not loading data from my web server and also it seems to be using myproj as the root context of the path. I am not sure what am I doing fundamentally wrong.

**Comment by nevir** [comment]
Sorry about the super delayed response!

WCT unfortunately doesn't really support external servers at the moment. Part of the trouble is that WCT needs to be able to generate a test index (and subsequently mount it somewhere), and also to serve its internal copies of `browser.js` and `environment.js`

However, as of https://github.com/Polymer/web-component-tester/commit/7411af52307ac84726d297af09623b9d743a4e3d, you should be able to hook into WCT's own express server (and mount your own):

`wct.conf.js`:
```js
module.exports = {
  registerHooks: function(wct) {
    wct.hook('prepare:webserver', function(app, done) {
      app.use(...);
      done();
    });
  },
};
```

**Comment by nevir** [comment]
Closing, but please feel free to reopen if you run into issues
