### ISSUE TITLE
Support standard Bower package layouts

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/web-component-tester#152]
WCT should work when dependencies are installed into the standard location of `bower_components/`, or whatever the `.bowerrc` file points to if there is one.

**Comment by justinfagnani** [comment]
@morethanreal FYI

**Comment by nevir** [comment]
Done! https://github.com/Polymer/web-component-tester/commit/1f0abf4c6ba42efd164691b1824257a0badfe8c4

**Comment by morethanreal** [comment]
:+1:
