### ISSUE TITLE
flush(callback) method does not work with sinon.useFakeTimers

### ISSUE THREAD

**Issue by oderby** [Polymer/web-component-tester#153]
I'm guessing because it just assumes no one mucks with the global setTimeout methods. In particular, running the following using wct 

```js
suite('AwesomeLib', function() {
  this.timeout(1000);
  setup(function() {
    this.clock = sinon.useFakeTimers();
  });
  teardown(function() {
    this.clock.restore();
  });
  test('is awesome', function(done) {
    // ... assume we do something async here.
    flush(function() {
      assert.isTrue(true);
      done();
    });
  });
});
```

results in mocha failing the test with error "timeout of 1000ms exceeded". 

Perhaps the fix is to do something like what Mocha did (capture the desired global timer methods): https://github.com/mochajs/mocha/issues/237

**Comment by nevir** [comment]
Ugh, good catch! Yeah, I'll keep a reference around to the original timers
