### ISSUE TITLE
missing 2.15-x64-chromedriver

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/web-component-tester#154]
As of this morning, I get an error when running web component tester via it's grunt task :

```
$ grunt wct-test
Running "wct-test:local" (wct-test) task
Starting Selenium server for local browsers
Error: Missing .../node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
Warning: Error: Missing .../node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver Use --force to continue.

Aborted due to warnings.
```

I guess some version problem in a dependency?

Using Ubuntu 14.10.

**Comment by nevir** [comment]
Hmm, this looks like fallout from https://github.com/Polymer/wct-local/issues/8

As a stopgap, can you try uninstalling wct and reinstalling it, to force `wct-local` to cache the latest copy of selenium?

**Comment by nevir** [comment]
Alright, this should not occur as of `wct-local` `1.4.1` (it'll attempt to grab the latest copy of selenium at runtime, if it's missing)
