### ISSUE TITLE
File syntax error results in silent failure

### ISSUE THREAD

**Issue by oderby** [Polymer/web-component-tester#155]
If I omit the close brace for a test suite (see sample below) in my test file, the file is silently skipped and no error is reported. If I run wct in persistent mode and inspect the dev console, I see an error:  
> :37304/foo.test.html?bust=0.19621555414050817:169 
> Uncaught SyntaxError: Unexpected end of input' (as expected).

Although this shouldn't happen very often (good code editors/jshint should prevent it), I think it's a bug that wct doesn't report the error.

```javascript
describe("awesomeness", function() {
  it('should work', function() {
      expect(1).to.equal(1);
});
```

**Comment by garlicnation** [comment]
+1 This has bit me often.
