### ISSUE TITLE
Question: Tooling for running WCT in visual studio?

### ISSUE THREAD

**Issue by dsschnau** [Polymer/web-component-tester#156]
Hi Polymer folks,

We have incorporated polymer into the UI for our .NET application. We're researching incorporating unit tests into our application. Does the tooling exist for running WCT tests in visual studio (and also on TFS)? Can anyone point us in the right direction?

**Comment by nevir** [comment]
Hmm, I'm not aware of any VS specific tooling (as external node packages).

What does VS expect in a test runner? (I'm guessing a specific output format, at minimum)
