### ISSUE TITLE
Testing IE through local VM

### ISSUE THREAD

**Issue by indolering** [Polymer/web-component-tester#157]
I was trying to follow [this guide](https://theplant.jp/en/blogs/24-automated-browser-testing-on-internet-explorer-with-capybara) for running selenium against a VirtualBox IE install.  It looks like support for remote instances is limited to SauceLabs, is that correct?

**Comment by nevir** [comment]
You should be able to do this (though it's not very well documented, sorry)! WCT can talk to any webdriver server

Roughly following step 4 of that guide, I think the following will work:

`wct.conf.js`:
```js
module.exports = {
  // This is a list of webdriver capabilities objects, with the addition of a `url` property.
  activeBrowsers: [
    {
      url: "http://<CI Selenium Hub>:4444/wd/hub", // Whatever hub you spun up in step 3.5.
      // Adapted from http://selenium.googlecode.com/svn/trunk/docs/api/rb/Selenium/WebDriver/Remote/Capabilities.html#internet_explorer-class_method
      browserName: "internet explorer",
      platform: "windows",
      takesScreenshot: true,
      cssSelectorsEnabled: true,
    }
  ]
};
```

**Comment by nevir** [comment]
I'm going to close this, but feel free to command and/or reopen if you run into troubles!

**Comment by indolering** [comment]
Is there a documentation repo somewhere that we could add this to?  I would like to see this getting added to the primary documentation : )
