### ISSUE TITLE
Compatibility with 0.8-style directory layout

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/web-component-tester#158]
This is probably already on your radar based on the work in https://github.com/PolymerLabs/seed-element/tree/0.8-preview, but the recommended directory and relative path structure in 0.8 has changed, and the web server started via the `wct` command doesn't play nicely with those changes. (I think it's `selenium`'s built in web server?)

https://github.com/Polymerlabs/polyserve works around this, and it's possible to start `polyserve` and then manually run the tests by opening the corresponding page in a browser, but you lose some of the automation.

**Comment by nevir** [comment]
Just landed this in `master` with https://github.com/Polymer/web-component-tester/commit/1f0abf4c6ba42efd164691b1824257a0badfe8c4
