### ISSUE TITLE
Specifying browser versions and platforms via command line

### ISSUE THREAD

**Issue by rnicholus** [Polymer/web-component-tester#164]
How can I ensure tests are run against specific browser versions on specific platforms **via the command line**? I would like to do this via for sauce tests.

For example, if I'd like to run my tests on Safari 8 on OSX 10.10 and Chrome beta on Windows 7.1, how would I modify the following command?

```bash
wct --sauce chrome,safari
```

I don't see any mention of platform or version specification in the docs.

**Comment by nevir** [comment]
Yeah, sorry, that bit's not documented very well :( The following should work:

    wct --sauce "OS X 10.10/Safari@8" --sauce "Windows 7/Chrome@beta"

**Comment by rnicholus** [comment]
Ah, cool. Thanks!
