### ISSUE TITLE
Local Npm module "web-component-tester" not found. Is it installed?

### ISSUE THREAD

**Issue by sesteva** [Polymer/web-component-tester#165]
I used the yeoman generator-polymer which installed web-component-tester version 2.2.3 and everything was working fine with polymer 0.5.*

I've updated my app to test 0.8 api and I noticed WCT was waiting for the polymer-ready event. I've found the issue in github and the fixed included in version 3.1.3 of web-component-tester.

I updated my package.json to install 3.1.3 instead. Installation was successful.
When I try to run grunt test:local I get the following error:

     Local Npm module "web-component-tester" not found. Is it installed?
     Warning: Task "wct-test:local" not found. Use --force to continue.

Gruntfile looks like this:

    module.exports = function (grunt) {
    require('time-grunt')(grunt);
    require('load-grunt-tasks')(grunt);
    grunt.loadNpmTasks('web-component-tester');
    [..]
    'wct-test': {
      local: {
        options: {remote: false}
      },
      remote: {
        options: {remote: true}
      }
    },

I've tried uninstall and re-installing. This only happens to me with this version. Grunt is not able to find that package.

**Comment by clubajax** [comment]
I'm having the same problem. I wonder if it's because the package doesn't contain a main or index.

**Comment by clubajax** [comment]
Ping.

To be clear, the only way I can get testing to work is with the global wct command. I can't get it to work in any script.

**Comment by clubajax** [comment]
I figured it out. i was missing the async callback.

    grunt.registerTask('test', function () {
        var
            done = this.async(),
            wct = require('web-component-tester'),
            options = {};
        wct.test(options, function () {
            done();
            process.exit(0);
        });
    });

**Comment by justinfagnani** [comment]
Closing for now, because this is kind of old and seems to have a resolution. Feel free to reopen if it's still an issue.
