### ISSUE TITLE
Question: Is it possible to pipe console.* messages to stdout?

### ISSUE THREAD

**Issue by fearphage** [Polymer/web-component-tester#170]
I want to see the `console.log` messages in my terminal/test runner. Is that currently possible?

**Comment by nevir** [comment]
Yeah, the WCT context returned by `test` emits `log:<level>` events among others (e.g. `log:info`, `log:error`, etc)

I've got a quick reference on the docs of https://github.com/Polymer/web-component-tester/blob/master/runner/test.js - also, the

**Comment by nevir** [comment]
Also, if you would rather just deal with a single stream, and WCT's default formatting, you can construct one of these guys: https://github.com/Polymer/web-component-tester/blob/master/runner/clireporter.js

(Also via `test({output: process.stdout})`

**Comment by fearphage** [comment]
Thanks for the quick response. I see it is possible programmatically. Is there a cli parallel to this though?

**Comment by justinfagnani** [comment]
Seems like the same at #15. There should be a flag for this.
