### ISSUE TITLE
Error: Mixing tdd and bdd Mocha styles is not supported.

### ISSUE THREAD

**Issue by Rich17** [Polymer/web-component-tester#174]
After completing the following, running the gold-cc-cvc-input test suites result in the error, "Mixing tdd and bdd Mocha styles is not supported. You called "afterEach". Did you mean "suiteTeardown"?"

1. Install gold-cc-cvc-input via bower from Polymer Elements
2. Install web-component-tester via bower
3. Install test-fixture via bower from Polymer/test-fixture
4. Install iron-test-helpers via bower from Polymer Elements
5. Navigate to http://localhost:3000/bower_components/gold-cc-cvc-input/test/index.html in chrome

I didn't have any installation issues with any of the above items. I did notice that Polymer/test-fixture uses two "or" statements that allow for afterEach or teardown, but removing "afterEach" didn't result in any changes. Thanks a lot for looking into this

![screen shot 2015-05-31 at 9 37 33 pm](https://cloud.githubusercontent.com/assets/11934871/7904987/85fd655a-07dd-11e5-884c-f71d0a715a21.png)

**Comment by blasten** [comment]
@Rich17 you should use `PolymerElements/test-fixture`
You can run `bower install PolymerElements/test-fixture#^1.0.0` to get the latest test-fixture

**Comment by torcellite** [comment]
@blasten I've install the latest version of the `test-fixture` within the test folder since it requires an older version of `webcomponents` and `polymer` requires the latest version. I referenced everything correctly but I'm still getting the error.

**Comment by draco1989** [comment]
Hi @Rich17 , what Mocha is telling you is that you're using "afterEach" functions which are meant to be used with BDD mocha style (describe, it...) and you should use "suiteTeardown" instead of "afterEach".

**Comment by justinfagnani** [comment]
Is this still an issue? Seems like a constraint by Mocha. Closing for now, feel free to reopen.
