### ISSUE TITLE
Stacky dependency breaks requirejs

### ISSUE THREAD

**Issue by jimsimon** [Polymer/web-component-tester#202]
Trying to use web component tester with code that uses requirejs causes an error.  Stacky checks for the existence of the require function, assumes it's running on node.js if it finds it, and tries to require a node module.  This breaks the test runner because the node module it's looking for does not exist on the client.

**Comment by jimsimon** [comment]
I submitted a PR on the Stacky project to resolve this.  I'm not sure if the PolymerLabs and Polymer orgs are under the same team(s), but if someone merges that PR in and bumps Stacky's version number, then I can submit a PR to use the bumped Stacky version in WCT.

https://github.com/PolymerLabs/stacky/pull/4

**Comment by azakus** [comment]
Stacky 1.2.3 with your PR is released, so I'll close this unless you are still having an issue.

**Comment by jimsimon** [comment]
I think the only part left is to update the dependency version in WCT to bring in the fix.  I was going to open a PR for it today, but got sidetracked.

**Comment by jimsimon** [comment]
I've opened https://github.com/Polymer/web-component-tester/pull/212 to update the Stacky dependency in WCT.
