### ISSUE TITLE
Polymer.dom.flush is not called when window.flush is called in tests using Polymer 1.0

### ISSUE THREAD

**Issue by mrdewitt** [Polymer/web-component-tester#203]
Looks like it's still looking for Polymer.flush (which doesn't exist in 1.0)

**Comment by mrdewitt** [comment]
see pull request #200

**Comment by justinfagnani** [comment]
Looks like this was fixed in https://github.com/Polymer/web-component-tester/commit/8aeb4dba9615199a3abf7ca4aa32c94df4d48233
