### ISSUE TITLE
HTTP Mocking in WCT

### ISSUE THREAD

**Issue by sankethkatta** [Polymer/web-component-tester#207]
What is the best way to mock HTTP requests with WCT tests?
In a server side app, I would have used a library such as [nock](https://github.com/pgte/nock). 
Is it possible to use nock here?

**Comment by apowers313** [comment]
You can use Sinon in a similar way to how you would use nock. For example, check out the [test for iron-ajax](https://github.com/PolymerElements/iron-ajax/blob/master/test/iron-ajax.html) and the [documentation for Sinon](http://sinonjs.org/docs/#fakeServer).

**Comment by sankethkatta** [comment]
Thanks! That's exactly what I was looking for.
