### ISSUE TITLE
404 errors for a11ySuite.js

### ISSUE THREAD

**Issue by apowers313** [Polymer/web-component-tester#209]
When running wct, I repeatedly get the error:
`404 GET /components/web-component-tester/runtime-helpers/a11ySuite.js`

It appears to be because [browser.js](https://github.com/Polymer/web-component-tester/blob/master/browser.js) includes `web-component-tester/runtime-helpers/a11ySuite.js` on line 505. It's annoying, but not fatal; however the volume of the errors just masks other 404 errors that might pop up.

**Comment by azakus** [comment]
Are you depending on an older version of wct in your bower.json?

**Comment by apowers313** [comment]
I installed 3.3.15 in the local node_modules via npm.

**Comment by azakus** [comment]
Oh, now I see what you mean. All of the elements I tested on had `web-component-tester` as a bower dependency, which would serve the a11ySuite file from the right spot.

**Comment by apowers313** [comment]
Seems like it could be global / local / bower / npm / etc... Lots of places to look for those files.

Maybe you could have a environment variable for the path to WCT?

**Comment by azakus** [comment]
Since wct knows how to serve browser.js correctly, I'll add it to that list and serve it from the installed wct location.
