### ISSUE TITLE
Tests run before bindings on page are complete

### ISSUE THREAD

**Issue by cbwhitebu** [Polymer/web-component-tester#213]
I have a test that fails when run from the command line or by launching the browser but succeeds if I reload the page. It looks like the tests are failing because they run before the bindings fire.

Is there some way to defer the test from running?

    <!doctype html>
    <html>
    <head>
        <meta charset="utf-8">
        <script src="../../bower_components/webcomponentsjs/webcomponents.min.js"></script>
        <script src="../../bower_components/web-component-tester/browser.js"></script>
        <link rel="import" href="./cbw-projector.html">
        <link rel="import" href="../../bower_components/iron-ajax/iron-ajax.html">
    </head>
    <body>
    <template is="dom-bind">
        <iron-ajax id="goalsQuery" url="./goals.json" last-response="{{savings}}"
               auto></iron-ajax>
        <cbw-projector balance="{{savings.balance}}" total-monthly-pledge="{{savings.totalMonthlyPledge}}" goals="{{savings.goals}}" id="projector"></cbw-projector>
    </template>
    <script>
        suite('<cbw-projector>',function(){
            test('binding',function(){
                var node=document.getElementById('projector');
                assert.equal(node.balance, 7000);
                assert.equal(node.totalMonthlyPledge,1500);
                assert.equal(node.goals.length,6,);
            });
        });
    </script>
    </body>
    </html>

**Comment by MartinsThiago** [comment]
Maybe you can try to use `fixture element`, with it you can have more control when things are stamped and also... clean your element state - [link](https://github.com/Polymer/test-fixture)

Or it can be failing for the first time because first load should take some more time... try to delay its execution with `done callback`... so your test should look like this:

```javascript
test('binding',function(done){
    setTimeout(function(){
            var node=document.getElementById('projector');
            assert.equal(node.balance, 7000);
            assert.equal(node.totalMonthlyPledge,1500);
            assert.equal(node.goals.length,6);
            done();
    }, 5000); //Delays 5s
});

```

**Comment by justinfagnani** [comment]
You can defer when a test completes by using the callback argument to the test function, or returning a Promise. From there you need to defer the start of real test work yourself by waiting on what resources you need.

I also second @MartinsThiago's suggestion of using `<text-fixture>`, which is automatically imported now.
