### ISSUE TITLE
Google Chrome not found in Arch Linux

### ISSUE THREAD

**Issue by panuhorsmalahti** [Polymer/web-component-tester#222]
I installed google-chrome from Arch Linux AUR, which uses the binary name 'google-chrome-stable', but web-component-tester doesn't look for it.

My workaround was creating a symbolic link:
```
sudo ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome
```

**Comment by BenoitPerrot** [comment]
To avoid modifying your system installation, you can instead tell launchpad where to find chrome via the dedicated environment variable:
```
export LAUNCHPAD_CHROME=/usr/bin/google-chrome-stable
```
This can be done for other browsers as well. More information on https://github.com/ekryski/launchpad.

**Comment by dman777** [comment]
:+1:
