### ISSUE TITLE
Should this be used for testing things other than web components?

### ISSUE THREAD

**Issue by devinivy** [Polymer/web-component-tester#223]
I've been using the web-component-tester for a little while now, and it has been great.  I'm wondering if there are any particularly good reasons to not use this as a glorified front-end testing suite– for projects that aren't necessary related to web components or Polymer.  I notice that the hydrolysis project did this to a degree.  The only reason that comes to mind is that it waits for web components / Polymer, but otherwise isn't this library quite multi-purpose?

**Comment by justinfagnani** [comment]
WCT can be multi-purpose, though it's pretty targeted at web components. It's main advantage is working well with HTML imports and setting up a good environment automatically. Other apps and libraries that use HTML imports would benefit from this.
