### ISSUE TITLE
Example sauce config leads to "Error: No browsers configured to run"

### ISSUE THREAD

**Issue by jyasskin** [Polymer/web-component-tester#250]
https://github.com/Polymer/web-component-tester#plugins gives the following example configuration:

```javascript
module.exports = {
  plugins: {
    sauce: {
      disabled: true,
      browsers: ['chrome', 'firefox']
    }
  },
};
```

However, using that `wct.conf.js` results in an error:

> [17:32:11] 'test:sauce' errored after 138 ms
> [17:32:11] Error: No browsers configured to run

**Comment by azakus** [comment]
Fixed with https://github.com/Polymer/web-component-tester/pull/254
