### ISSUE TITLE
Option to suppress debug sauce plugin debug output

### ISSUE THREAD

**Issue by justincy** [Polymer/web-component-tester#262]
https://github.com/Polymer/wct-sauce/blob/591644a0e6c2e0704ab6c0163cc04976f21cfe1f/lib/sauce.js#L48

That line prints the sauce configuration options which include the sauce username and access key. That makes wct difficult to use in a public ci setting like Travis.

Is there currently any way to suppress it?

**Comment by justinfagnani** [comment]
@azakus is this correct? We use sauce + Travis...

**Comment by azakus** [comment]
Ugh, that's so dumb.

**Comment by azakus** [comment]
Sorry, last comment was terse. You have to use the `--verbose` option to log that out, but it is kinda dumb to ever log that out anyway.

On Travis, the best recourse you have against leaking the keys is to use an encrypted environment variable, and the `sauce_connect` addon, as wct will use that tunnel without any chance of leaking the key itself.
