### ISSUE TITLE
Cannot stub more than 1 element?

### ISSUE THREAD

**Issue by malthusyau** [Polymer/web-component-tester#306]
When I tried to use replace() multiple times to stub out multiple elements, sinon complains:

> Error: Attempted to wrap instanceTemplate which is already wrapped
>     Object.wrapMethod at /components/sinon/sinon-1.12.1.js:1210
>           Object.stub at /components/sinon/sinon-1.12.1.js:3007
>           Object.with at web-component-tester/browser.js:1555
> 

Is replace() designed to be used more than once? Or is it only limited to only stub out 1 element?

**Comment by danmane** [comment]
I'm getting this too. Unfortunately it makes it impossible for me to use replace() for my testing. :(

Here's a repro.
https://gist.github.com/danmane/7761a63b662d044c36c2a5affdc69290

**Comment by danmane** [comment]
Thanks!

**Comment by klarkc** [comment]
The very same error is happening here, in the 4.3.1 version. Still not fixed?
