### ISSUE TITLE
Content selectors overridden when using replace

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/web-component-tester#331]
In WCT 4.3 `replace` breaks a content selector. A minimal reproducible case with shady dom:

```html
<dom-module id="my-element">
    <template>
      <other-element></other-element>
      <content-element>
        <div class="selector">
          Asdf
        </div>
      </content-element>
    </template>
  </dom-module>

  <dom-module id="other-element">
    <template>
      Other
    </template>
  </dom-module>

  <dom-module id="mock-element">
    <template>
      Mock
    </template>
  </dom-module>

  <dom-module id="content-element">
    <template>
      <content select=".selector"></content>
    </template>
  </dom-module>

  <test-fixture id="basic">
    <template>
      <my-element></my-element>
    </template>
  </test-fixture>

  <script>
    suite('Wrong replace tests', function() {
      var element;

      Polymer({is: 'my-element'});
      Polymer({is: 'other-element'});
      Polymer({is: 'mock-element'});
      Polymer({is: 'content-element'});

      setup(function() {
        replace('other-element').with('mock-element');
        element = fixture('basic');
      });

      test('does not replace correctly', function() {
        console.log(element);
      });

    });
  </script>
```

## Expected Behavior ##
Output on the screen (place a debug point on the `console.log`) should be "Mock Asdf"

## Actual Behavior ##
Output on the screen is only "Mock"

This is happening because the element fixture is replacing the other element with the mock element. However, consequently it is also removing the content selector. Then the content-element does not contain the content anymore and breaks the selector.

**Comment by 43081j** [comment]
I think I have this too, in my element I have:

```
<paper-item>foo</paper-item>
```

Using the `replace(...)` helper on any element seems to cause the `paper-item` to be empty.

**Comment by justinfagnani** [comment]
@e111077 can you take a look?

**Comment by e111077** [comment]
Yeah, I've noticed this with some internal tests. This causes `paper-input` to exception as well.
