### ISSUE TITLE
Generate JUnit formatted test output

### ISSUE THREAD

**Issue by potatogopher** [Polymer/web-component-tester#340]
I am using `web-component-tester` on Jenkins and it doesn't recognize my test and I believe it is because it is looking for a `junit.xml` file. Is there a way to generate this from the test cases that run?

**Comment by marcinkubicki** [comment]
We've  used the[ wct-junit-reporter](https://github.com/marcelmeulemans/wct-junit-reporter) plugin. It is very useful. :-)
