### ISSUE TITLE
`Replace` teardown issue

### ISSUE THREAD

**Issue by akc42** [Polymer/web-component-tester#360]
In trying to understand more about what is happening I have added some console.log statements to the `browser.js` file around the `replace` interface extension.

Specifically I added one in the teardown  callback function.

It is called once on my first test, and then increasingly one more time per test as each test is run.  So the second test it is called two times, the third test three times and so on.

This increasing number of calls does not seem to be effective by the `describe` blocks that I traverse.  Each `it` test run just increases the number by one.

**Comment by e111077** [comment]
Nice catch, I'll have a PR soon
