### ISSUE TITLE
geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz does not exist

### ISSUE THREAD

**Issue by jonniespratley** [Polymer/web-component-tester#371]
Your spelling is

`https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz`

Which does not exist. Change it to:

https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz

**Comment by azakus** [comment]
Looks like the naming schemes have changed _yet again_. 😡

**Comment by jonniespratley** [comment]
I have opened a issue on https://github.com/mozilla/geckodriver/issues/193

**Comment by jonniespratley** [comment]
Ok it looks like the guys at mozilla/geckodriver are NOT going to change the name of the release file, thus making this work will fall on this repo, or how ever you guys get the links for the drivers. Can we get this fix in?

**Comment by rictic** [comment]
We use selenium-standalone to download. https://github.com/vvo/selenium-standalone/issues/207 is the correct bug, and it sounds like `selenium-standalone@5.6.1` has the fix, so reinstalling should fix.
