### ISSUE TITLE
Wrong exit code returned

### ISSUE THREAD

**Issue by panuhorsmalahti** [Polymer/web-component-tester#375]
Hi, I'm still debugging this issue, but it seems like the `wct` cli command is returning an error code `0` instead of `1` when a test fails.

I've added a few console.logs:
```
Test run ended in failure: 1 failed tests
hook: cleanup

firefox 45 (4/0/1)

process.exit 0
```

The process.exit(0) is called in https://github.com/Polymer/web-component-tester/blob/master/bin/wct#L21

I'm using Node 6.4.0, npm 3.10.3 and running in a Docker container created by image specified here: https://github.com/MartinsThiago/polymer-tester
(Note that I'm currently just running /bin/bash and running the tests that way to investigate the issue).

I can also reproduce this on Mac OS X El Capitan and the same Node/npm versions.

I'm using web-component-tester@4.3.3, and the issue persists with 4.4.0-prerelease.1.

**Comment by rictic** [comment]
Can confirm, taking a look now.

**Comment by rictic** [comment]
PR out, hope to merge soon.

**Comment by rictic** [comment]
Fixed by v4.3.4

**Comment by rictic** [comment]
Thanks for the bug report!

**Comment by panuhorsmalahti** [comment]
Thanks for the quick response 👍, I can confirm the fix worked.
