### ISSUE TITLE
Upgrade to mocha v3, remove install warnings & errors

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/web-component-tester#396]
When you install wct or the Polymer CLI, you get the following errors:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

the last 3 of these all come from Mocha v2.x.x. Mocha has moved on to v3, where all of these warnings have been fixed. The update seems non-breaking for wct, however it may be breaking for our users if they were relying on weird behavior in their tests. See https://github.com/mochajs/mocha/pull/2350 for details.

How does everyone feel about preparing a new WCT major release, with a version bump up to Mocha v3 and any other breaking changes we've been waiting on?

**Comment by azakus** [comment]
👍

**Comment by maxknee** [comment]
https://github.com/Polymer/web-component-tester/pull/407
