### ISSUE TITLE
Install on a per project basis

### ISSUE THREAD

**Issue by lukasoppermann** [Polymer/web-component-tester#410]
Hey,

is it possible to install `web-component-tester` on a per project basis? I tried with `npm i web-component-tester` but when running `wct` I get `Could not find WCT plugin named "local"`. However installing it globally works. 😢 

I think installing it per project could be useful so that when other people contribute to a project they only have to run `npm i` without the need to install an additional global dependency.

**Comment by maxknee** [comment]
@lukasoppermann In your project path, you should be able to do `./node_modules/web-component-tester/bin/wct`
