### ISSUE TITLE
Why web-component-tester uses chai and mocha for unit testing. What are the benefits over other unit testing libraries

### ISSUE THREAD

**Issue by cmevawala** [Polymer/web-component-tester#434]

**Comment by marvinhagemeister** [comment]
I'm not on the wct team, but my guess is that most other libraries simply don't run in a browser environment. So jest, ava, tape and tap all don't fit that use case.

**Comment by FredKSchott** [comment]
Yup, both mocha and chai work great in the browser. We originally evaluated all the major testing libraries and frameworks and decided on the set you see in wct today.

Feel free to join us in the #tools channel on Slack if you'd like to discuss more!
