### ISSUE TITLE
Travis failed with "java is not present on your PATH"

### ISSUE THREAD

**Issue by butterandfly** [Polymer/web-component-tester#438]
All stuff that using wct are failed in travis build. I'm trying to add some java dependence to the yaml.

**Comment by azakus** [comment]
This is an upstream travis issue: https://github.com/travis-ci/travis-ci/issues/6928
Should be fixed in tomorrow's travis build environment update: https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264931280

**Comment by butterandfly** [comment]
It's fixed.
