### ISSUE TITLE
Detect that wct hasn't been installed in the package

### ISSUE THREAD

**Issue by rictic** [Polymer/web-component-tester#439]
… and die with a helpful error message

**Comment by TimvdLippe** [comment]
Installing `web-component-tester` master globally and following the instructions, I still can't run `wct` in my project. Reason being that in `bower.json`, ignore contains `*`. Therefore it ignores `package.json` and this file is not installed. The check opens `package.json`, but discovers it is not found and therefore will not run `wct`. Could you remove the ignored file in the `bower.json`?

To reproduce:

1. Install `wct` globally on latest master
2. `npm install && npm run build` in global directory to generate working bin
3. In project install with bower `polymer/web-component-tester#master`
4. See the error is thrown, even though `wct` is installed locally

**Comment by rictic** [comment]
Good catch Tim, tracking that bug at #447
