### ISSUE TITLE
Prove out variant testing end to end in an element

### ISSUE THREAD

**Issue by rictic** [Polymer/web-component-tester#440]

**Comment by rictic** [comment]
Blocked on variants installation, so handing this to Justin

**Comment by justinfagnani** [comment]
What's blocked?

**Comment by rictic** [comment]
Oh, did `polymer install` land?

**Comment by justinfagnani** [comment]
yep!

**Comment by rictic** [comment]
I'll take a shot at getting this working with the 2.0 branch of an element then

**Comment by rictic** [comment]
Looks like things are shaping up pretty well: https://travis-ci.org/PolymerElements/paper-checkbox/builds/182130781

**Comment by justinfagnani** [comment]
I think we're good here.
