### ISSUE TITLE
Ignoring package.json in our bower.json breaks #439

### ISSUE THREAD

**Issue by rictic** [Polymer/web-component-tester#447]
Reported by @TimvdLippe here: https://github.com/Polymer/web-component-tester/issues/439#issuecomment-266003418

**Comment by rictic** [comment]
This suggests that we should probably look for bower.json inside the client side repo, as we currently match the semver range `4 - 6` but old bower packages don't have a package.json

**Comment by TimvdLippe** [comment]
The bower.json is also hidden, since all files are ignored. I think the easiest fix is adding `!package.json` to the ignore array.

**Comment by rictic** [comment]
I want to be backwards compatible too though, so that if you have a bower dependency on wct 4 client side (with the old version of mocha that it came with) then the node test-runner side of wct 6 should work with that if at all possible.

When I do bower install web-component-tester I see `bower_components/web-component-tester/.bower.json`. Looks like I may need to look for one of a set of files…

**Comment by rictic** [comment]
Not ignoring package.json and bower.json also seems wise.
