### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/web-component-tester#448]
Depends on:
  - [x] https://github.com/Polymer/wct-local/issues/50
  - [x] https://github.com/Polymer/web-component-tester/pull/474

**Comment by rictic** [comment]
Also blocked by local issues here: https://github.com/Polymer/web-component-tester/milestone/2

**Comment by rictic** [comment]
All known issues in wct's server side are finished, I think now it's just a matter of stamping versions for wct-local and wct-sauce (and maybe polyserve)

**Comment by justinfagnani** [comment]
Would like to get a new polyserve in there.

**Comment by justinfagnani** [comment]
Would like to get a new polyserve in there.

**Comment by rictic** [comment]
New polyserve is in as of prerelease.2
