### ISSUE TITLE
using console.log inside a test shows only the first line

### ISSUE THREAD

**Issue by fairsayan** [Polymer/web-component-tester#470]
When a run this code:

```
        test('should run automatically', function(done) {
          var backend = fixture('auto');
          assert.equal(backend._url, Config.apiBaseUrl + backend.url);
          assert.equal(backend.auto, true);

          backend.$.ajax.addEventListener('request', function () {
              server.respond();
          });
          backend.$.ajax.addEventListener('response', (event) => {
            console.info(event);
            done();
          });
        });
```

I obtain a collapsible row in my javascript console, but I can see only the first line.
I'm using Chrome 55.0.2883.95 on Mac.

<img width="1179" alt="screen shot 2016-12-31 at 11 45 10" src="https://cloud.githubusercontent.com/assets/897578/21577106/02950502-cf4f-11e6-83bc-1f663df04ee7.png">
<img width="1177" alt="screen shot 2016-12-31 at 11 45 19" src="https://cloud.githubusercontent.com/assets/897578/21577107/0295251e-cf4f-11e6-98e3-c9992324d0cf.png">

**Comment by FredKSchott** [comment]
I believe this happens when the JavaScript engine has already garbage collected the object. You could confirm by saving the event to an array or map and seeing if this still happens.

Unfortunately I don't think there's much we can do here, this is V8 / Chrome behavior
