### ISSUE TITLE
Global `flush` should probably call `Polymer.Templatizer.flush` as well.

### ISSUE THREAD

**Issue by blasten** [Polymer/web-component-tester#475]
In Polymer 2.0, `Polymer.dom.flush` doesn't flush the work scheduled by templatizer anymore.  Therefore,`window.flush` should probably also call `Polymer.Templatizer.flush` when available.

cc @e111077, @FredKSchott

**Comment by kevinpschaaf** [comment]
The intention is for `Polymer.dom.flush` to call `Polymer.Templatizer.flush`, so the change should be in Polymer, covered by: https://github.com/Polymer/polymer/issues/4062

**Comment by justinfagnani** [comment]
Ok, then closing this one.
