### ISSUE TITLE
wct not working with alacarte polyfills

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/web-component-tester#485]
`whenWebComponentsReady` will assume that there will be a `WebComponentsReady` event fired at some point, but that might not be the case for people just importing only certain polyfills.
It should be enough to check for:
```js
if (!window.WebComponents) {
  done();
} else if (WebComponents.whenReady) {
  WebComponents.whenReady(function() {
  //....
```

@azakus wdyt?

**Comment by justinfagnani** [comment]
Any changes on what the polyfills will provide here?

**Comment by valdrinkoshi** [comment]
`HTMLImports` continues to provide `HTMLImports.whenReady()`.
`CustomElements` doesn't have `CustomElements.flush()` callback.
`WebComponents` still fires `WebComponentsReady` event.

**Comment by rictic** [comment]
I think this was resolved by https://github.com/Polymer/web-component-tester/pull/537

**Comment by valdrinkoshi** [comment]
Correct, WCT now will wait for `WebComponentsReady` if necessary, or just call `done`. Users that have different timing requirements should setup the `waitFor` function e.g. if the user is only using html-imports polyfill, he should setup tests like this:
```js
WCT = {
  waitFor: function(callback) {
    HTMLImports.whenReady(callback);
  }
}
