### ISSUE TITLE
Incorrect warning about not having web-component-tester installed as a dependency

### ISSUE THREAD

**Issue by pghalliday** [Polymer/web-component-tester#486]
I have updated to the latest alpha of polymer-cli which includes an alpha of web-component-tester (I'm trying to get the istanbul plugin to work) and I noticed this odd warning:

```
    The web-component-tester node module is not installed as a dependency of
    this project (app).

    We recommend that you run this command to add it:
        npm install --save-dev web-component-tester

    or run:
        yarn add web-component-tester --dev

    Doing so will ensure that your project is in control of the version of wct
    that your project is tested with, insulating you from any future breaking
    changes and making your test runs more reproducible. In a future release
    of wct this will be required.

    Expected a directory to exist at: /Users/pghalliday/projects/github/pghalliday-boilerplate/polymer-firebase-boilerplate/app/node_modules/web-component-tester/
```

The thing is I'm not running the tests in the root of my project so my node_modules directory is actually a directory up and web-component-tester is of course installed.

Am I to expect that a breaking change is coming that will prevent me from organizing my project this way.

The polymer stuff is not the only part of my app so I have things separated to keep me sane. However I only maintain one package.json at the top level which then exposes all my build and test scripts.

**Comment by marybeshaw** [comment]
What is in your .bowerrc file?  We got the same error because we renamed our bower_components directory to components.

**Comment by pghalliday** [comment]
I don't have a .bowerrc everything is default. I'm pretty sure the problem is because bower_components is not next to node_modules, it's in a sub directory. But I don't think web-component-tester should assume the location of node_modules and should search for it properly (it can be in any parent path)

**Comment by justinfagnani** [comment]
What directory are you running `polymer test` from?

**Comment by rictic** [comment]
@justinfagnani Correct me if I misrecall, but I seem to recall that the plan of record is that we don't currently plan to require a local node install of wct (waiting on beginning the ecosystem migration to yarn at the least, maybe renaming wct's node module). If that's the case, I think we should drop this warning for the time being. WDYT?

**Comment by rictic** [comment]
Taking a different tact, we could resolve this by getting the root directory from polymer.json and resolving wct from there.

**Comment by justinfagnani** [comment]
This is the check for the bower dependency not the npm dependency

**Comment by pghalliday** [comment]
@justinfagnani the project laid out as follows 

- node_modules
- ui - polymer stuff
- app - pure js stuff in es6

I switch to the ui directory to run polymer test. I switch to app to run NYC and mocha.

@rictic - would be good to not require a local installation but my other point is that in this scenario there is a local install in the normal search path (ie. A parent directory)

**Comment by pghalliday** [comment]
@justinfagnani the error states the node_modules directory. It is installed in bower_components, however bower_conponents is not in the same directory as node_modules. Which given other comments, might be the root cause

**Comment by andrewmiroshnichenko** [comment]
Hi!
I'm tried to run polymer test on the component that comes out-of-box with polymer init and here what I got:
```
andreym@jadlocal:~/Projects/test/polymer/testfolder$ polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 44822

    The web-component-tester node module is not installed as a dependency of
    this project (testfolder).

    We recommend that you run this command to add it:
        npm install --save-dev web-component-tester

    or run:
        yarn add web-component-tester --dev

    Doing so will ensure that your project is in control of the version of wct
    that your project is tested with, insulating you from any future breaking
    changes and making your test runs more reproducible. In a future release
    of wct this will be required.

    Expected a directory to exist at: /home/andreym/Projects/test/polymer/testfolder/node_modules/web-component-tester/

chrome 55                Beginning tests via http://localhost:8000/components/testfolder/generated-index.html?cli_browser_id=0
chrome failed to maximize
chrome 55                ✖ test/testfolder-element_test.html » testfolder-element » instantiating the element works

  expected undefined to equal 'testfolder-element'
    <unknown> at   Context.<anonymous> at testfolder-element_test.html:25:0

chrome 55                Tests failed: 1 failed tests
firefox 52               Beginning tests via http://localhost:8000/components/testfolder/generated-index.html?cli_browser_id=1
firefox failed to maximize
firefox 52               ✖ test/testfolder-element_test.html » testfolder-element » instantiating the element works

  expected undefined to equal 'testfolder-element'
    <unknown> at                             AssertionError at /components/chai/chai.js:5553:0
    <unknown> at   [3]</module.exports/Assertion.prototype.assert at /components/chai/chai.js:206:0
    <unknown> at           [6]</module.exports/assert.equal at /components/chai/chai.js:2277:0
    <unknown> at                                  <unknown> at testfolder-element_test.html:25:0

firefox 52               Tests failed: 1 failed tests
Test run ended in failure: 1 failed tests

chrome 55 (0/0/1)                       firefox 52 (0/0/1)                    


Error: 1 failed tests

error:   cli runtime exception: Error: 1 failed tests
error:   Error: 1 failed tests
    at /usr/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at next (native)
    at fulfilled (/usr/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

```
I don't have used npm and WCT supposed to be found in bower_components, not node_modules. Can tests fail becase of that?

**Comment by rictic** [comment]
I've proposed that we remove this warning here: https://github.com/Polymer/web-component-tester/pull/500

**Comment by andrewmiroshnichenko** [comment]
Ok, but even if warning will be removed, test on "polymer component from scratch" will fail.
I mean that probably tests in current polymer env (that can be get with `polymer init`) aren't working. And this warning just indicate this situation.
