### ISSUE TITLE
WCT 5.0.0 broken with latest test-fixture release 3.0.0-rc.1

### ISSUE THREAD

**Issue by owendismuke** [Polymer/web-component-tester#498]
Copy pasta from polymerelements/test-fixture#45

The issue is two-fold:

WCT@5 does not reference a version of test-fixture in package.json (but a version is referenced in bower.json). This allows for exactly this issue to happen.
Adding dependency in test-fixture to WCT@6 has caused WCT@5 to fail on machines with less than Typescript 2.2.x.  

In an app using Typescript 2.1.6, I receive the below errors on a build. The errors are most likely caused by a dependency of WCT@6. However, I did notice that test-fixture variant 1 has a dependency on WCT@4 - WCT@4.9x and test-fixture variant 2 has a dependency on WCT@6+. I would think variant 2 should have a dep on WCT@5 - WCT@5.9x, and variant 3 start the dependency on WCT@6.

### Expected outcome

The app builds without an issue because I specified a specific version of WCT

### Actual outcome
```
Error: Build:']' expected.
Error: Build:';' expected.
Error: Build:Declaration or statement expected.
Error: Build:']' expected.
Error: Build:')' expected.
Error: Build:Declaration or statement expected.
Error: Build:Declaration or statement expected.
Error: Build:Declaration or statement expected.
```  

### Steps to reproduce

1. Add WCT@5 to a project
2. Limit that project to typescript@~2.1.6
3. Write tests referencing /components/web-component-tester/browsers.js
4. Require WCT into gulp
5. Build project.

### Original message below
Test-fixture just bumped from 2.0.1 to 3.0.0-rc. Now WCT@5.0.0 cannot build with Typescript less than 2.2. Thus, our TS 2.1.x build is broken.

I was able to get a successful local build of our app after removing test-fixture@3.0.0-rc.1's dependency on WCT@6.

The typescript 2.2 req probably boils down to a dependency of WCT@6, but I needed WCT@5 back in action, so that's the route I went. Too tired at the moment to put words in an order that will be helpful.

**Comment by sohail-surge** [comment]
I just found the same issue. Unfortunately, we need to use Typescript 2.1

**Comment by DanielGarciaMandillo** [comment]
**"test-fixture": "PolymerElements/test-fixture"**

In the package.json of all versions: the project PolymerElements/test-fixture is pointing to "master" branch instead a specific version. This is breaking my project

**Comment by owendismuke** [comment]
@rictic: Is WCT@5.0.1 package.json still going to point to the **master** branch of **PolymerElements/test-fixture** instead of a specific version level?

**Comment by rictic** [comment]
I'm confused, what is the connection between test-fixture and typescript?

**Comment by owendismuke** [comment]
Test-Fixture 3.0.0-rc.1 (master branch version) Has a dependency on WCT@6.0.0-Prerelease.x (4 or 5, I can't remember). WCT 6 introduced (when this bug was filed) dependency on an @types library that breaks in TS below 2.2.

**Comment by owendismuke** [comment]
@rictic Here's a repo that errors: [owendismuke/wct-5](https://github.com/owendismuke/wct-5)

Steps to reproduce:

1. clone repo
1. `npm install`
1. `gulp`


```
[19:17:21] Using gulpfile /DevRoot/git/wct-5/gulpfile.js
[19:17:21] Starting 'default'...
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(57,63): error TS2304: Cannot find name 'Promise'.
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(75,44): error TS2304: Cannot find name 'Promise'.
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(77,57): error TS2304: Cannot find name 'Promise'.
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(80,68): error TS2304: Cannot find name 'Promise'.
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(83,67): error TS2304: Cannot find name 'Promise'.
/DevRoot/git/wct-5/node_modules/@types/mz/index.d.ts(86,69): error TS2304: Cannot find name 'Promise'.
...
```

```
$ npm ls @types/mz
wct-5@0.0.1 /DevRoot/git/wct-5
└─┬ web-component-tester@5.0.1
  └─┬ test-fixture@3.0.0-rc.1 (git://github.com/polymerelements/test-fixture.git#eb86ce25c850bb20523d47a55d07235f0fad5858)
    └─┬ web-component-tester@6.0.0-prerelease.7
      └─┬ polyserve@0.16.0-prerelease.9
        └── @types/mz@0.0.29
```
