### ISSUE TITLE
[Feature Request] Mock Interactions

### ISSUE THREAD

**Issue by chrismbeckett** [Polymer/web-component-tester#527]
It would be much more convenient if web-component-tester included a set of mock interactions like those provided by the iron-test-helper package without having to import a separate library.

**Comment by rictic** [comment]
The issue with bundling more libraries in WCT is that then the test runner is versioned with your test libraries, so the more libraries we ship the more version constraints we add to your projects, and the harder it is to upgrade to a new version of WCT (or to upgrade the test libraries that are shipped with WCT).

Our plan is actually to go in the opposite direction and ship fewer things by default. It would be nice for `polymer init` to install and include a bunch of test libraries for you though. Filed as https://github.com/Polymer/polymer-cli/issues/659 to track
