### ISSUE TITLE
Browsers - PhantomJs

### ISSUE THREAD

**Issue by sesteva** [Polymer/web-component-tester#56]

**Comment by nevir** [comment]
Alright, with WCT `2.2` nearly out; it seems doable to write a `wct-phantom` plugin to enable this. Probably not going to be something we'll want to tackle directly, though

**Comment by alexanderatallah** [comment]
Why was this closed? Is someone working on wct-phantom? It's a pretty important thing for continuous integration if you don't want to use Sauce stuff.

**Comment by Klathmon** [comment]
@alexanderatallah I don't think phantomjs will even run Polymer or webcomponents at this time. According to [this](https://github.com/Polymer/polymer/issues/724) you may have to wait until PhantomJS V3 to use webcomponents with it.

**Comment by nevir** [comment]
@alexanderatallah also, it's not something we're going to have time to build ourselves, but with the plugin system, it should be possible to make a plugin that allows WCT to run on top of phantom. We'd definitely accept issues for any shortcomings w/ the plugin interface to make that easier

**Comment by rafalradomski** [comment]
Any plans about that?
