### ISSUE TITLE
7.0

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/web-component-tester#582]
We need a new major version to support npm and ES6 module workflows.

## Requirements:

1. Do not require bower installation of the client dependencies
2. Support projects where client dependencies are installed flat (ie, `yarn install --flat`)
3. Either allow included client dependencies to be `import`ed, or stop bundling client dependencies.
4. Support new `polyserve` flags like `--npm`.

## Rough Sketch

- Create a separate `wct-browser` package that includes only the minimum libraries needed to communicate with a test instance. This package should work in flat installations.
- Create a `wct-browser-legacy` package that depends on `wct-browser`, but adds all the implicit dependencies that WCT 6.0 includes.

It may also be a good time to update how we use Selenium.

**Comment by justinfagnani** [comment]
Depends on https://github.com/Polymer/polyserve/issues/208

**Comment by justinfagnani** [comment]
cc @usergenic

**Comment by justinfagnani** [comment]
We've been able to do this without a new major version.

**Comment by 0xR** [comment]
Is there another issue for WCT with NPM with a minor version change? I want to track the progress and this issue is now closed.

**Comment by justinfagnani** [comment]
WCT had worked with npm since the `--npm` flag was added a couple of minor versions back.
