### ISSUE TITLE
web-component-tester 6.1.2 cannot be installed using yarn

### ISSUE THREAD

**Issue by Artur-** [Polymer/web-component-tester#598]
`yarn add web-component-tester@6.1.2`

yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error The package undefined@undefined requires a flat dependency graph. Add `"flat": true` to your package.json and try again.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Was it really intentional to upgrade the test-fixture dependency to v3.0.0-pre.1 in 6.1.2?

**Comment by daniele-orlando** [comment]
Same here.

**Comment by justinfagnani** [comment]
The problem is that we're depending on test-fixture 3.0-preview. We should roll that back and move all the npm support changes into 7.0

**Comment by JosefJezek** [comment]
@justinfagnani Please resolve asap

**Comment by usergenic** [comment]
web-component-tester 6.1.3 published 🎉  and polymer-cli 1.5.2 published 🎉  to resolve this issue.

**Comment by daniele-orlando** [comment]
Thank you very much!
