### ISSUE TITLE
WCT hangs when running test on IE11 (Windows 10)

### ISSUE THREAD

**Issue by fcontigiani-namirial** [Polymer/web-component-tester#602]
web-component-tester/browser/config.js, line 13:

var useNpm = document.currentScript.src.match(/wct-browser-legacy\/browser.js/) // ...

document.currentScript is undefined on IE11

**Comment by gwicks** [comment]
Having the same issue here

**Comment by usergenic** [comment]
PR #603 removes use of currentScript for this and should make things work again on IE11.  Working on getting this released.

**Comment by usergenic** [comment]
web-component-tester 6.1.4 published 🎉

**Comment by usergenic** [comment]
please update your wct

**Comment by usergenic** [comment]
issue not completely fixed.  there's a follow-up release coming shortly.

**Comment by usergenic** [comment]
wct 6.1.5 and polymer-cli 1.5.4 published 🎉 <- *actually* fixes this
