### ISSUE TITLE
Look into supporting headless chrome

### ISSUE THREAD

**Issue by usergenic** [Polymer/web-component-tester#613]
Could be useful for filesystem watching based fast-feedback workflows.

**Comment by LarsDenBakker** [comment]
What about opening up the selenium capabilities for external configuration, and just set some sane defaults. That way you stay flexible into the future.

**Comment by aomarks** [comment]
This might also simplify running a WCT test on travis, since you wouldn't need to start an X server.

**Comment by stramel** [comment]
:sweat_smile: Was digging into this today, guess I should have started here!

**Comment by LarsDenBakker** [comment]
Any progress on this? It would save a lot of execution time

**Comment by luckyincode** [comment]
Is there support for any headless browser?

**Comment by jaichandra** [comment]
headless works for both Chrome 59+ and Firefox 56+ now. Use below config in `wct.conf.json`
```
{
  "verbose": false,
  "plugins": {
    "local": {
      "disabled": false,
      "browsers": ["chrome", "firefox"],
      "browserOptions": {
        "chrome": ["window-size=1920,1080", "headless", "disable-gpu"],
        "firefox": ["--headless"]
      }
    }
  }
}
```

**Comment by stramel** [comment]
**NOTE:** if using Headless Chrome with Travis containerized (`sudo: false`) you will need the flag `no-sandbox`
**NOTE:** `window-size` is not specifically needed.

```json
{
  "verbose": false,
  "plugins": {
    "local": {
      "disabled": false,
      "browsers": ["chrome", "firefox"],
      "browserOptions": {
        "chrome": ["headless", "disable-gpu", "no-sandbox"],
        "firefox": ["--headless"]
      }
    }
  }
}
```

**Comment by stramel** [comment]
@usergenic @azakus Can this be closed now?

**Comment by usergenic** [comment]
Oh yeah that's a good point.  Thanks, @stramel :)
