### ISSUE TITLE
npm flag - document.getElementById(...).create is not a function

### ISSUE THREAD

**Issue by silenceisgolden** [Polymer/web-component-tester#642]
Trying to use the `--npm` flag is causing

```
Error: Error thrown outside of test function: document.getElementById(...).create is not a function
```

This might be a duplicate of #505 but since that one was closed and fixed, I'm re-opening in a new issue. I am using Chrome 61. [See this PR for more info](https://github.com/abstract-elements/abstract-mixin-lit-html/pull/5) or this [failed build](https://circleci.com/gh/abstract-elements/abstract-mixin-lit-html/32?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

A contributing factor to this might be

```
Failed to load resource: the server responded with a status of 404 (Not Found)
sinon.js Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/components/test-fixture/test-fixture.html Failed to load resource: the server responded with a status of 404 (Not Found)
async.js Failed to load resource: the server responded with a status of 404 (Not Found)
sinon.js Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
async.js Failed to load resource: the server responded with a status of 404 (Not Found)
sinon.js Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/components/test-fixture/test-fixture.html Failed to load resource: the server responded with a status of 404 (Not Found)
async.js Failed to load resource: the server responded with a status of 404 (Not Found)
2sinon.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

I am using the command `wct -l chrome --npm --compile never` on Windows 10 with Node 8 and WCT 6.3.

**Comment by usergenic** [comment]
@silenceisgolden  `:8081/components/test-fixture/test-fixture.html` looks wrong.  Test fixture in the npm universe should not be loaded by-way of HTML import, as it is now vended as a node module in npm package '@polymer/test-fixture' which should be a dep of `wct-browser-legacy`.

Other possible reason for that line would be if you imported the old url directly in your test file by using a `<link rel="import" href="../../test-fixture/test-fixture.html">` or something...

Be sure you're on latest wct-browser-legacy too.  Latest is `0.0.1-pre.10`.  It's about stable enough we can move it into something more semver friendly soon, but that's the latest.

**Comment by felixzapata** [comment]
hi, in my case to fix this issue with Polymer 1.x and with the version 6.4.3 of WCT installed via npm:

- install via bower `PolymerElements/test-fixture#^1.0.0`
- add inside my test file these includes:

`<link rel="import" href="YOUR_ROUTE_TO/bower_components/test-fixture/test-fixture.html">`

`<script src="YOUR_ROUTE_TO/public/bower_components/test-fixture/test-fixture-mocha.js"></script>`
