### ISSUE TITLE
Working behind a corporate proxy.

### ISSUE THREAD

**Issue by diregraph** [Polymer/web-component-tester#645]
I have the following error when trying to run `wct` command.

`Error: Could not download https://selenium-release.storage.googleapis.com/2.53/IEDriverServer_x64_2.53.1.zip: Error: connect ETIMEDOUT 74.125.200.128:443`

How to set up proxy config in WTC? Is it configured in the wct.conf.json file?

**Comment by vlaraort** [comment]
Hi @diregraph, did you solved that? I am facing the same issue
