### ISSUE TITLE
Web Component Tester Hangs at end of Test Suite

### ISSUE THREAD

**Issue by djpetti** [Polymer/web-component-tester#648]
I'm having a strange issue that appears to have started with WCT 6.4.0. Initially, I thought it was caused by Selenium, but I confirmed that a configuration with the exact same versions of Selenium, chromedriver, etc. but an older version of WCT seems to work.

I am running on Ubuntu 16.04.

The problem that I have is that when I run ```polymer test```, all the tests complete successfully, and then it just hangs at the end. I don't see anything in the verbose output that indicates that something abnormal happened.

[Here](https://gist.github.com/djpetti/56a46c8159251361661ce98d31a601db) is a copy of the output from wct with ```--verbose.``` (You can see after line 583 where it hung and I eventually killed it.)

I'm curious to know if anyone else is experiencing this, and, if so, how they solved it.

UPDATE: Everything works fine on WCT 6.3.0.

**Comment by hastebrot** [comment]
>I'm curious to know if anyone else is experiencing this, and, if so, how they solved it.

I also experiencing this. Hangs on Travis. Reverting from WCT 6.4.0 to 6.3.0 helped.

**Comment by ankon** [comment]
I've started to see the same behavior with 6.4.0. Adding a forced dependency on ~6.3.0 (and then wiping the caches in travis!) helped.

**Comment by rednil** [comment]
I ran into the same issue using 6.4.0 with node-8.9.1. Downgrading to node-6.11.2 resolved it for me, even with 6.4.0

**Comment by bennypowers** [comment]
I've got this issue in GitLab CI (ubuntu-based docker image)

**Comment by ZarekParker** [comment]
We are having this issue as well, with node 6.11.2 and a forced downgrade to 6.3.0

**Comment by djpetti** [comment]
It seems I spoke too soon, as this week, the problem reappeared. Downgrading node did not solve it. Interestingly, everything works fine on my local machine, but not on Docker, even though they appear to have the same versions of all the relevant software, AFAIK. I'll have to do some more digging. Anyone else experienced a relapse?

**Comment by rictic** [comment]
We fixed this issue in https://github.com/Polymer/wct-local/pull/67

The issue is that wct and wct-local must agree on their version of cleankill. If you're using the latest versions of both, things should be fine. If you're using wct@6.4.0 then you need wct-local@2.0.16. If you're using wct@6.3.0 you need wct-local@2.0.15

**Comment by djpetti** [comment]
Confirming that this issue seems to be fixed with wct 6.4.0 and wct-local 2.0.16.

**Comment by ankon** [comment]
> The issue is that wct and wct-local must agree on their version of cleankill. If you're using the latest versions of both, things should be fine. If you're using wct@6.4.0 then you need wct-local@2.0.16. If you're using wct@<6.4.0 you need wct-local@<2.0.16

Should this not be made visible in web-component-tester's package.json? i.e. declare the dependency on wct-local ^2.0.16, and release web-component-tester 6.4.1?

**Comment by rictic** [comment]
+1 @ankon. Sent out https://github.com/Polymer/web-component-tester/pull/653 for review

**Comment by rictic** [comment]
Stamped v6.4.1 with that hard constraint on wct-local
