### ISSUE TITLE
Async and lodash injections extraneous

### ISSUE THREAD

**Issue by e111077** [Polymer/web-component-tester#683]
I cannot find any place as to where the [injected async.js and lodash.js](https://github.com/Polymer/web-component-tester/blob/master/browser/config.ts#L47) are used by the browser. It seems as if these were first put into wct 3 years ago.

By removing these, I could not find a package that failed testing.

**Comment by e111077** [comment]
ping @usergenic @azakus

**Comment by e111077** [comment]
related #674

**Comment by justinfagnani** [comment]
@e111077 What packages did you look at? Any that we don't own?

**Comment by e111077** [comment]
Spoke offline: I did not check packages that we didn't own. Closing issue as we may end up going a completely different direction
