### ISSUE TITLE
Project Security

### ISSUE THREAD

**Issue by hyperpress** [Polymer/web-component-tester#725]
NPM solved one problem but introduced another in the form of security vulnerabilities in dependencies and potential for introducing them.  I realize we can't be responsible for what devs might introduce into their own projects, but:

Does the Polymer project have a dedicated security team who is constantly monitoring on required dependencies, including PSK examples? If so, who is leading that?

I know if we find a potential vulnerability in a specific dependency it should  be reported there, but if we find one that just needs an update where should we be submitting security issues? Here, or elsewhere? 

I've already had one corporate client inquire about this and I don't feel like I can adequately address their questions, which are quite legitimate. So any clarification would really help.

Comments?

**Comment by mikesamuel** [comment]
I'm from Google's Security Engineering.  We monitor Polymer, and are happy to receive security reports via https://goo.gl/vulnz

> I know if we find a potential vulnerability in a specific dependency it should be reported there

Please don't report security vulnerabilities via public issue trackers.  https://goo.gl/vulnz will receive reports and work with you to route them, and manage disclosure.

For reference, the overarching project's [contribution guidelines](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#contributing-code-to-the-polymer-library) say:
> Polymer also participates in Google's Patch Rewards Program, where you can earn cold, hard cash for qualifying security patches to the Polymer library. Visit the patch rewards page to find out more.

The PRP is different from VRP (vulnerability rewards), so I don't know if Google pays for vulnerability reports for Polymer, but can find out if you're interested.

**Comment by hyperpress** [comment]
Thanks @mikesamuel. Appreciate clarification on contact point. Noted.

Closing as answered.
