### ISSUE TITLE
Extract saucelabs and local runners into plugins

### ISSUE THREAD

**Issue by thedeeno** [Polymer/web-component-tester#75]
I think mixing vendor specific concepts into the code base makes it harder to understand the server side logic. Where does `wct` end and `sauceLabs` start? Further this architecture makes it more difficult to add new runners in the future.

I propose we extract the existing runners into pluggable modules. I imagine an interface like this:

`wct --sauce linux/firefox@32 --local chrome --my-custom-runner safari`

This eliminates the concept of 'remote/local' and replaces it with a more standardized and extensible vocabulary.

I think I understand enough about what's going on to do this. Is this a patch you'd accept?

**Comment by nevir** [comment]
Alrighty, I finally have time - I'm nabbing this!

**Comment by nevir** [comment]
Done!

**Comment by thedeeno** [comment]
Hell yes!
