### ISSUE TITLE
Don't include external libraries in `environment.js`

### ISSUE THREAD

**Issue by thedeeno** [Polymer/web-component-tester#89]
The consumer of WCT should have control over the utility libraries they want to include. Also it frees the maintainer from having to update them. We should consider removing `sinon` and `sinon-chai` from the automatically included dependencies.

In our specific case, we're trying to add our own `sinon.chai` matchers and can't because `WCT` is including it's own version.

**Comment by nevir** [comment]
So I'm starting to think that we could just serve the assets split up; and give the user access to the list of files served to disable serving of whatever they don't want

**Comment by thedeeno** [comment]
That sounds like a simple and straight forward solution.
Compression/concatenation isn't necessarily a priority at test time. It'll
probably make things obvious to new users as well.
